updated inputs to use HOC instead of reusing same input
fullfacing/radio-ui pull request #208
Opened 2020-09-28 12:29 UTC by alastairmcqueen

## Description

Brief description of changes made e.g. bug fix for broken Ajax container.

## Related tickets

Any Jira tickets related to the changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] I have lint my changes locally.
- [ ] I have formatted my changes locally.
- [ ] I have updated any relevant documentation.
- [ ] I have added tests to cover my changes.
- [ ] I have checked that all new and existing tests passed.
- [ ] I have checked to ensure there aren't other open Pull Requests for the same update/change.

2020-09-28 12:33 UTC, alastairmcqueen commented on src/components/select/index.js
> +const Select = props => <Input {...props} fullWidth noRef />;
It's a component, I assure you the label is there

2020-09-28 12:53 UTC, MikeyAlmighty approved these changes

2020-09-28 12:53 UTC, MikeyAlmighty commented on src/components/select/index.js
> +const Select = props => <Input {...props} fullWidth noRef />;
@accesslint fight me

2020-09-28 13:23 UTC, Pdut89 commented on src/components/with-input-wrapper/styles.js
> +export const StyledContainer = styled(Flex).attrs(() => ({
[dust] Can use shorthand:
```
export const StyledContainer = styled(Flex).attrs({
  flexDirection: 'column'
})`
```

2020-09-28 13:24 UTC, Pdut89 approved these changes

2020-09-28 15:04 UTC, GaryGeorgeu commented on src/components/time-input/index.js
> +const TimeInput = props => <Input {...props} type="time" step="1" />;
Not sure if this `type="time"` is handled on the component itself using a custom time selector, or if you are using the standard `type="time"` attribute for an input. 

If you aren't using a custom time selector component, then just note that the `type="time"` isn't natively supported in safari, IE, or edge.
https://caniuse.com/input-datetime

2020-09-28 15:06 UTC, GaryGeorgeu approved these changes

2020-09-29 06:44 UTC, alastairmcqueen commented on src/components/time-input/index.js
> +const TimeInput = props => <Input {...props} type="time" step="1" />;
@GaryGeorgeu good catch, i'll have to implement something to fix that

2020-09-29 07:14 UTC, tiaanduplessis requested changes

2020-09-29 07:14 UTC, tiaanduplessis commented on src/components/with-input-wrapper/styles.js
> +export const StyledContainer = styled(Flex).attrs(() => ({
Agreed. I was mistaken previously regarding this syntax being removed. It appears only to be the case for subfunctions https://github.com/styled-components/styled-components/blob/master/CHANGELOG.md#v500---2020-01-13

2020-09-29 07:14 UTC, tiaanduplessis commented on src/components/with-auto-complete/index.js
> +  const ListOptions = () =>
Can we try and move these components out of render?

2020-09-29 07:14 UTC, tiaanduplessis commented on src/components/time-input/index.js
> +const TimeInput = props => <Input {...props} type="time" step="1" />;
You should be able to add a polyfill, tho quality varies

2020-09-29 07:26 UTC, alastairmcqueen commented on src/components/with-auto-complete/index.js
> +  const ListOptions = () =>
Will give it a go

2020-09-29 09:28 UTC, mantonides approved these changes

2020-09-29 11:06 UTC, merged