updated time input
fullfacing/radio-ui pull request #283
Opened 2020-11-12 13:07 UTC by alastairmcqueen

## Description

Brief description of changes made e.g. bug fix for broken Ajax container.

## Related tickets

Any Jira tickets related to the changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have lint my changes locally.
- [x] I have formatted my changes locally.
- [ ] I have updated any relevant documentation.
- [ ] I have added tests to cover my changes.
- [ ] I have checked that all new and existing tests passed.
- [ ] I have checked to ensure there aren't other open Pull Requests for the same update/change.

2020-11-12 13:22 UTC, tiaanduplessis requested changes

2020-11-12 13:22 UTC, tiaanduplessis commented on src/components/time-input/index.js
> +      onChange={e => {
Move up and wrap in use callback since it is being passed to the underlying input component. Also, rename `e` to `event`

2020-11-12 13:22 UTC, tiaanduplessis commented on src/components/time-input/index.js
> +        const { value } = target;
I'd probably write `const { value } = event.target` to avoid creating an intermediate variable, but this is a micro optimization and a matter of preference

2020-11-12 13:22 UTC, tiaanduplessis commented on src/components/time-input/index.js
> +      type="time"
One thing to note is that the input of `type='time'` is not supported in IE11 and Safari. I polyfill will need to be used.

2020-11-12 14:17 UTC, MikeyAlmighty commented on src/components/time-input/index.js
> +      type="time"
@alastairmcqueen After a quick search: https://www.npmjs.com/package/react-time-input-polyfill
not sure if that's what you're going for

2020-11-12 14:18 UTC, MikeyAlmighty commented on src/components/time-input/index.js
> +      type="time"
https://github.com/Dan503/time-input-polyfill

2020-11-12 14:51 UTC, GaryGeorgeu approved these changes

2020-11-13 10:38 UTC, MikeyAlmighty approved these changes

2020-11-13 11:14 UTC, merged